### PR TITLE
Adding video tutorial solutions to the repo

### PR DESCRIPTION
**Pull request by knathanieltucker**
I've been using these tutorials for lesson materials for my class over a General Assembly for years. And help the students, we would often go over these activities in class. On that note, to help students that missed the class or wanted extra help, I will went ahead and made some YouTube videos of me going through some of these activities.  I felt that if they helped my students it would probably help other students out there as well. And if you do see these as helpful, I would be happy to make more of them for the Internet as well as students.

I totally understand if this is not the place for these materials, or if you would like them to be added in different way. I'm totally down for coming up with constructive solutions.

I love your activities and keep on caring on regardless!!

### CODE REVIEW

**Comment by guipsamora** [comment]
Hi @knathanieltucker , thank you a lot for your message and the PR!

Really cool videos! I think it definitely adds value to others that might learn better with other inputs like videos or want to do a double check on their thought process/code. I really appreciate your effort on creating and sharing them!

Keep up the good work and the PRs!

**Comment by knathanieltucker** [comment]
Thanks @guipsamora - I've made the video public here: https://www.youtube.com/watch?v=jL3EVCoYIJQ

Thanks for the callout!

**Comment by guipsamora** [comment]
Thanks @knathanieltucker! I really appreciate all the videos you have done!

**Comment by knathanieltucker** [comment]
Absolutely!

**Pull request merged**
